# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5fd336c3e80a66f8455a40fc087303875bc91e3c06604126edd0df77452e1affbd946f59ed50ab70720b9df075114e4ee07c0555a500678c5a31d9fb4586e71

test:
  secret_key_base: b733a8e3d04bf4bbba044a864c6cadbec72fdf91a91bb9925132dd598dfe144a160033838754d90bc29c7693cb4d3cf8822afc6c417e4948f3308ff5bdb60d33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
